  
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - redhat.vscode-xml
    - redhat.vscode-commons
    - redhat.fabric8-analytics
    - vscjava.vscode-java-debug
    - vscjava.vscode-maven
    - vscjava.vscode-java-test
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - redhat.java
    - github.vscode-codeql