#--------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
# This file contains a custom dock configuration that Gitpod will use for the underlying image for the Gitpod 
# borwser IDE.
# For useful context regarding custom Dockerfiles and images for GitPod see this 
# link https://www.gitpod.io/docs/config-docker
#--------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------
FROM gitpod/workspace-full